on:
  push:
    paths-ignore:
      - "**.md"
      - "CNAME"
    branches:
      - master

  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Run pwsh
        shell: pwsh
        run: |
          Get-Content index.html
          (New-Guid).Guid | Out-File index.html
          Get-Content index.html
      - name: Commit and push changes
        run: |
          git config --global user.name "robot"
          git config --global user.email "robot@libertysandwich.com"

          git add -A
          git commit --allow-empty --allow-empty-message -m "\"
          git push
